---
title: "Map Making"
author: "Logan Williams"
date: "4/2/2020"
output: html_document
---

```{r}
library(here)       #file path management
library(readr)
library(ggplot2)
library(sf)
library(dplyr)
library(RColorBrewer)
library(ggsn)
```

```{r}
#load data
df <- read_csv(here("data", "clean_data.csv"))

#load shapefiles
stl <- read_sf(here("data", "shapefiles", "stl_city.shp"))

cnty <- read_sf(here("data", "shapefiles", "stl_county.shp"))

stclr <- read_sf(here("data", "shapefiles", "stclair.shp"))

madison <- read_sf(here("data", "shapefiles", "madison.shp"))

tot <- read_sf(here("data", "shapefiles", "tot.shp"))
```

```{r}
#join shapefiles with clean data
stl_shp <- left_join(stl, df, by = c("GEOID"))
cnty_shp <- left_join(cnty, df, by = "GEOID")
stclr_shp <- left_join(stclr, df, by = "GEOID")
madison_shp <- left_join(madison, df, by = "GEOID")
tot <- left_join(tot, df, by = "GEOID")
```

```{r}
#map college educated
ggplot() + 
  geom_sf(data = stl_shp, mapping = aes(fill = colgrad))+
  geom_sf(data = cnty_shp, mapping = aes(fill = colgrad))+
  geom_sf(data = stclr_shp, mapping = aes(fill = colgrad))+
  geom_sf(data = madison_shp, mapping = aes(fill = colgrad))+
  scale_fill_viridis_c(name = "Population with no \nComputer or Internet (%)")+
  labs(
    title = "2018 St Louis Region College Educated Population",
    subtitle = "By Logan Williams",
    caption = "Data from Social Explorer and the US Census through the ACS"
  )  +
  theme_void()
```

```{r}
#map minority pop
ggplot() + 
  geom_sf(data = stl_shp, mapping = aes(fill = pct_min))+
  geom_sf(data = cnty_shp, mapping = aes(fill = pct_min))+
  geom_sf(data = stclr_shp, mapping = aes(fill = pct_min))+
  geom_sf(data = madison_shp, mapping = aes(fill = pct_min))+
  scale_fill_viridis_c(name = "Minority Population (%)")+
  labs(
    title = "2018 St Louis Region Minority Population",
    subtitle = "By Logan Williams",
    caption = "Data from Social Explorer and the US Census through the ACS"
  )  +
  theme_void()
```

```{r}
#map poverty
ggplot() + 
  geom_sf(data = stl_shp, mapping = aes(fill = pct_pov))+
  geom_sf(data = cnty_shp, mapping = aes(fill = pct_pov))+
  geom_sf(data = stclr_shp, mapping = aes(fill = pct_pov))+
  geom_sf(data = madison_shp, mapping = aes(fill = pct_pov))+
  scale_fill_viridis_c(name = "Population Living at\nor Below Poverty")+
  labs(
    title = "2018 St Louis Region Poverty",
    subtitle = "By Logan Williams",
    caption = "Data from Social Explorer and the US Census through the ACS"
  )  +
  theme_void()
```

```{r}
#map internet access
ggplot() + 
  geom_sf(data = tot, mapping = aes(fill = pct_nocom))+
  scale_fill_viridis_c(name = "Population with no \nComputer or Internet (%)")+
  labs(
    title = "2018 St Louis Region Internet Access",
    subtitle = "By Logan Williams",
    caption = "Data from Social Explorer and the US Census through the ACS"
  )  +
  theme_void()
```

